#!/bin/bash

PHP_BIN="$(which php)"

php artisan migrate -n --force
php artisan config:cache -n

{ crontab -l; echo "*/1 * * * * ${PHP_BIN} /var/www/artisan schedule:run >> /dev/null 2>&1"; } | crontab -

cron -f